export const SET_EARTH_DATE = "SET_EARTH_DATE";
export const SET_CAMERA = "SET_CAMERA";
export const FETCH_PHOTOS_PENDING = "FETCH_PHOTOS_PENDING";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_FAILED = "FETCH_PHOTOS_FAILED";
